task: segmentation

backbone:
  type: ResNet
  layers: 50

neck:
  type: FPN
  in_channels: [512, 1024, 2048]
  out_channels: 256

head:
  type: SegHead
  in_channels: [256, 256, 256]
  num_classes: 21
  hidden_dim: 256

