task: segmentation
algorithm: YOLO11Segmenter

backbone:
  type: YOLOBackbone
  depth: 0.50
  width: 0.25
  max_channels: 1024

neck:
  type: YOLOPAN
  in_channels: [128, 128, 256]
  out_channels: [64, 128, 256]
  depth: 0.50
  c3k: false

head:
  type: YOLOSegmentHead
  in_channels: [64, 128, 256]
  num_classes: 80
  reg_max: 16
  nm: 32
  npr: 64

postprocess:
  conf: 0.25
  iou: 0.45
  imgsz: 640
