task: segmentation
algorithm: YOLO11Segmenter

backbone:
  type: YOLOBackbone
  depth: 1.00
  width: 1.00
  max_channels: 512
  c3k2_12_c3k: true
  bottleneck_k: 3

neck:
  type: YOLOPAN
  in_channels: [512, 512, 512]
  out_channels: [256, 512, 512]
  depth: 1.00
  c3k: true
  bottleneck_k: 3

head:
  type: YOLOSegmentHead
  in_channels: [256, 512, 512]
  num_classes: 80
  reg_max: 16
  nm: 32
  npr: 256

postprocess:
  conf: 0.25
  iou: 0.45
  imgsz: 640
