task: detection

backbone:
  type: YOLOBackbone
  depth: 1.00
  width: 1.00
  max_channels: 512
  sppf_cv1_act: false
  sppf_residual: true
  c3k2_12_c3k: true
  bottleneck_k: 3  # Ultralytics 26l uses 3x3 in c3k2_1/c3k2_2 C3k

neck:
  type: YOLOPAN
  in_channels: [512, 512, 512]
  out_channels: [256, 512, 512]
  depth: 1.00
  c3k: true
  a2c2f: true
  bottleneck_k: 3  # Ultralytics 26l neck C3k all use 3x3

head:
  type: YOLOHead
  in_channels: [256, 512, 512]
  num_classes: 80
  reg_max: 1

postprocess:
  conf: 0.35
  nms_iou: 0.45
  end2end: true
