task: detection

# 转换后的权重（python tools/convert_ultralytics.py --model yolo26n.pt --out weights/yolo26n_converted.pth）
# weights: weights/yolo26n_converted.pth

backbone:
  type: YOLOBackbone
  depth: 0.50
  width: 0.25
  max_channels: 1024
  sppf_cv1_act: false
  sppf_residual: true

neck:
  type: YOLOPAN
  in_channels: [128, 128, 256]
  out_channels: [64, 128, 256]
  depth: 0.50
  c3k: true
  a2c2f: true

head:
  type: YOLOHead
  in_channels: [64, 128, 256]
  num_classes: 80
  reg_max: 1

postprocess:
  conf: 0.25
  nms_iou: 0.45
  end2end: true
